---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-gh
  namespace: test-system
spec:
  interval: 10m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/tiesmaster/flux-role-and-rolebinding-issue-with-service-accounts.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: test-system
spec:
  interval: 10m0s
  path: ./clusters/agd
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: test-gh
