---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-gh
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: minikube
  timeout: 1m0s
  url: https://github.com/tiesmaster/flux-test.git
